Description: Realtime person heatmap
Engine: gotpl
Home: http://kuberlab.com
Icon: https://storage.googleapis.com/kuberlab/static/favicon.ico
Keywords:
- kubernetes
- Artificial Intelligence
- tensorflow
- kibernetika
- pytorch
- kserving
- ml-serving
Maintainers:
- Email: nmahotkin@kibernetika.ai
  Name: Mahotkin Nikolay
Name: realtime-heatmap
Version: 1.0.0
