# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: Remove yum.conf proxy settings
  lineinfile:
    dest: /etc/yum.conf
    regexp: "^proxy=.*"
    state: absent
