# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

docker_name: "ia_video_analytics"
docker_image: "{{ docker_registry_address }}/{{ docker_name }}:{{ eis_version }}"
camera_stream_port: 9000
camera_stream_results_port: 65013
clients_list: "Visualizer"
app_name: "VideoAnalytics"
peer: "client"
cert_name: "etcd_{{ app_name }}_cert"
key_name: "etcd_{{ app_name }}_key"
publisher_pod_service: "ia-video-ingestion-service"
helm_release_name: "video-analytics-release"
helm_chart_analytics: "{{ helm_charts_location }}/video-analytics"
