apiVersion: v1
kind: Service
metadata:
  name: {{ include "niotis.fullname" . }}
  labels:
    {{- include "niotis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-port
      protocol: TCP
  selector:
    {{- include "niotis.selectorLabels" . | nindent 4 }}
