# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Exium Inc.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.appName }}
    name: {{ .Values.name }}
    version: {{ .Values.version }}
  annotations:
    prometheus.io/scrape: {{ .Values.env.enableMetrics | quote }}
    prometheus.io/scheme: "http"
    prometheus.io/port: {{ .Values.env.metricsPort | quote }}
    prometheus.io/path: {{ .Values.env.metricsSuffix | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      name: {{ .Values.name }}
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        name: {{ .Values.name }}
        version: {{ .Values.version }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.ipcPort }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_SVCNAME
              value: {{ .Values.name }}
            - name: REDIS_MASTER_ADDR
              value: {{ .Values.env.redisMaster }}
            - name: REDIS_SLAVE_ADDR
              value: {{ .Values.env.redisSlave }}
            - name: JEAGER_SERVER_ADDR
              value: {{ .Values.env.jaegerServer }}
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel }}
            - name: TRACING_ENABLED
              value: {{ .Values.env.enableTracer | quote }}
            - name: METRICS_ENABLED
              value: {{ .Values.env.enableMetrics | quote }}
            - name: METRICS_SUFFIX
              value: {{ .Values.env.metricsSuffix }}
            - name: METRICS_PORT
              value: {{ .Values.env.metricsPort }}
            - name: NATS_ENABLED
              value: {{ .Values.env.enableNats | quote }}
            - name: NATS_SERVER
              value: {{ .Values.env.natsServer }}
            - name: SESS_DB_TYPE
              value: {{ .Values.env.sessdbType }}
            - name: EXOPS_NATS_URL
              value: {{ .Values.env.exopsNatsUrl }}
            - name: CFG_NODE_NAME
              value: {{ .Values.env.cfgNodeName }}
            - name: CFG_NODE_TYPE
              value: {{ .Values.env.cfgNodeType }}
