# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: sdewan-selfsigned-issuer
  namespace: "{{ .Values.namespace }}"
spec:
  selfSigned: {}

