# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

# Global variables for host [openness_controller]
# Will override local variables from defaults

---

eis_install_path: "/opt/eis"
helm_charts_location: "{{ eis_install_path }}/charts"
eis_integ_path: "{{ eis_install_path }}/etcd/eis_integ"
etcd_certs_location: "{{ eis_install_path }}/etcd/Certificates"


os_yum_base_packages: "python3,python3-pip"
ca_default_bits: "{{ lookup('env', 'SSL_KEY_LENGTH') }}"

k8s_eis_namespace: "eis"

# Ceritficates settings
san_ca: "DNS:{{ pod_name }}-service"

cert_days: 3650
eis_openssl_cnf: "{{ eis_sources_dir }}/docker_setup/provision/config/openssl.cnf"

rootca_cert_name: "ca_certificate.pem"
rootca_key_name: "ca_key.pem"
rootca_location: "{{ etcd_certs_location }}/rootca"
rootca_key: "{{ rootca_location }}/{{ rootca_key_name }}"
rootca_cert: "{{ rootca_location }}/{{ rootca_cert_name }}"
rootca_subj: "/CN=EISCertToolSelfSignedtRootCA/L=$$$$/"

root_client_cert: "{{ etcd_certs_location }}/root/root_client_certificate.pem"
root_client_key: "{{ etcd_certs_location }}/root/root_client_key.pem"

eis_secrets_path: "/run/secrets/eis"
