# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Exium Inc.

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.name }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: 1
  targetCPUUtilizationPercentage: 85
